### ISSUE TITLE
Cosmic Cove Crashes

### ISSUE THREAD

**Issue by SuperHackio** [SunakazeKun/SMG2-Project-Template#1]
Steps to re-create:
Step 1: Install Project Template
Step 2: Do nothing but install the Project Template
Step 3: Load game and go to Cosmic Cove Galaxy
Step 4: Crash game

I have no idea why this occurs, but it's something to do with `PowerStarEventKeeper::initStarInfoTableAfterPlacement((void))`

**Comment by SunakazeKun** [comment]
Can you provide me with a full crash log please.

**Comment by SuperHackio** [comment]
![image](https://user-images.githubusercontent.com/44330283/147777256-96f45f2d-f727-4d01-a716-6f0253d2252b.png)

**Comment by SunakazeKun** [comment]
I think I've found the solution to this crash. I'll provide a fix asap

**Comment by SunakazeKun** [comment]
Check out the prerelease "Silvester Patch". The crashes should be fixed now.
